version: v1.0
name: Production deployment pipeline
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  - name: Deploy to prod
    task:
      secrets:
        - name: prod-creds
      jobs:
      - name: Deploy to prod
        commands:
          - echo "deploying...."
          - echo "done"

  - name: "Smoke tests"
    task:
      jobs:
      - name: Smoke
        commands:
          - echo "make smoke"
